 - name: install and run nodejs
   hosts: web
   become: yes # -b
   tasks:
   - name: install nodejs
     ansible.builtin.package:
      name: nodejs
      state: present
   - name: start the nodejs
     ansible.builtin.package: 
      name: nodejs
      state: started 
   
   
   

