- name: install packages
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item }}" # item will loop packages
      state: installed
    loop:
    - gcc
    - mysql
    - zip
    - git