- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefined variable
    ansible.builtin.debug:
      msg: "Hello {{ person | default ('Ravindra') }}"

  - name: convert string to list
    vars:
      fruits: "apple, guvava, sapota, papaya" #string
    ansible.builtin.debug:
      msg: "Fruits are :  {{  fruits  | split (',')  }}" 


  - name: convert map into list
    vars:
      course:
        name: ansible
        duration: 20hrs
        trainer:  siva
    ansible.builtin.debug:
      msg: "course info: {{ course | dict2items }}"      

  - name: convert loist into map
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}  
      - {'key': 'duration', 'value': '20hrs'} 
      - {'key': 'trainer', 'value': 'siva'} 
    ansible.builtin.debug:
      msg: "course info: {{ course | items2dict }}"  


