- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefined variable
    ansible.builtin.debug:
      msg: "Hello {{ person | default ('Ravindra') }}"

  - name: convert string to list
    vars:
      fruits: "apple, guvava, sapota, papaya" #string
    ansible.builtin.debug:
      msg: "Fruits are :  {{  fruits  | split (',')  }}" 


  - name: conver map into list
    vars:
      courses:
        name: ansible
        duration: 20hrs
        trainer:  siva
    ansible.builtin.debug:
      msg: "course info: {{ course | dict2items}}"      


