---
- hosts: web 
  become: true 
  tasks: 
    - name: Install Nginx 

        name: nginx 
        state: present 
        update_cache: true 

    - name: Start Nginx service 
    
        name: nginx 
        state: started 
        enabled: yes 

  